language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9
script: mvn install -Dgpg.skip=true '-DtestVectorZip=https://github.com/awslabs/aws-encryption-sdk-test-vectors/raw/master/vectors/awses-decrypt/python-1.3.8.zip'
sudo: false
dist: trusty
